# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "oiGSf5DZM6vjVcJVuuydiJWE2lGWrVT67249SwPAe1sokHKqmo6/I9eiMFslP4stemstoJDiP4EMgf79D9JBENGM0EmLsFaU/HEPQKWM+QZQsyKAOLfR4sIKUZlMVQuWePBcmAntLUTGAIaGstoWe9tfzAG5hLZO/utEEc9xtTKe4NDWbl3bV3DqlnMPcq11Gl2qSrG948oVeZoWtNiTly3w6QKc/9Dy5Mpfl/BZ/K6MWYJt+dCzcSZiGgseqXSLs6zabPTkz9MMXO7FH+qa643J5yebnzZ3CtHlcpL/EQ23D5VeQfqQNhqh/guWhZLK/HejBPJLedC8PMQ+oN/Evpb7Ox9l0nM5P4dDWggYcCv84kNBssFFIMHpp+6W89G9iMRbt+bFhVTrhHV0s9uFCzyN1woMKlkhqeClwifqcy6clmfD2uqSfkDLuY//i4yb0nBto/dQ4ETdZopkGTxi45Fv6CXgAEJJ0lj52gEdTeQcGKTogpi3YZ4X5K77zl8hqZFC2i0JkI+9OhwvGXQlYqNzxAwZdrOdS34XdEXsUzePnn+noizwyoGospWJzHUU+gkn+MU8Lht++5XTYac9a1SIVqp9NgIef9UP7kxsG06OjyAI+tcnVOwsLmU47VePKN3NxqnOtfhA1c/AyXQEI/7wJ6aMZIjeRf2garbKm0I="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
